{
  "SchemaVersion": 2,
  "CreatedAt": "2025-09-20T22:59:26.132625-04:00",
  "ArtifactName": "glinsky/devsecops-multilang:v1.2.0",
  "ArtifactType": "container_image",
  "Metadata": {
    "Size": 2380823040,
    "OS": {
      "Family": "ubuntu",
      "Name": "20.04",
      "EOSL": true
    },
    "ImageID": "sha256:d5eb3fd2362919e93f5508c0fe1dcabda6c089c02bc76b369fe34613001d7460",
    "DiffIDs": [
      "sha256:37250a17e932419f4b54e624c819baf38c0025e7f9c4ba0e15af15f14a3d74c3",
      "sha256:f285a80895c537447a3af1aeb534e77e7074cfc0fc63ad3b8d4ac9539ec90eae",
      "sha256:19d688abc07463fa0a04b64bde341879eda4dfd6d02476ba8a3dc2061acde116",
      "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e",
      "sha256:c863fef0e8f8649e5598387fb11477e70e1242d34418782c9a51af388c6051f1",
      "sha256:4162fdb4031ba1de37011c5a9d6aff2f1c70103e3b5663b394b469581405e656",
      "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0",
      "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b",
      "sha256:18d41a068f1d775a1ded11049b2553072ee671ddbcf5905bbbbeac50044f3513",
      "sha256:fc8eff637fb0b182b66636c55c1041a52bb9f067170944ec1c36e99c0528574c"
    ],
    "RepoTags": [
      "glinsky/devsecops-multilang:latest",
      "glinsky/devsecops-multilang:v1.0.0",
      "glinsky/devsecops-multilang:v1.2.0"
    ],
    "RepoDigests": [
      "glinsky/devsecops-multilang@sha256:b400e1bd4ab1ee670386ce34f80753048e488198f83e0dd0b827276cb62c2e03"
    ],
    "ImageConfig": {
      "architecture": "arm64",
      "created": "2025-09-20T23:10:44.889697546Z",
      "history": [
        {
          "created": "2025-04-08T10:46:43Z",
          "created_by": "/bin/sh -c #(nop)  ARG RELEASE",
          "empty_layer": true
        },
        {
          "created": "2025-04-08T10:46:43Z",
          "created_by": "/bin/sh -c #(nop)  ARG LAUNCHPAD_BUILD_ARCH",
          "empty_layer": true
        },
        {
          "created": "2025-04-08T10:46:43Z",
          "created_by": "/bin/sh -c #(nop)  LABEL org.opencontainers.image.ref.name=ubuntu",
          "empty_layer": true
        },
        {
          "created": "2025-04-08T10:46:43Z",
          "created_by": "/bin/sh -c #(nop)  LABEL org.opencontainers.image.version=20.04",
          "empty_layer": true
        },
        {
          "created": "2025-04-08T10:46:45Z",
          "created_by": "/bin/sh -c #(nop) ADD file:2c90d89e4dd4e1d2473deca816f585a78ced2a0c5c799399810f86fdbb17ac7e in / "
        },
        {
          "created": "2025-04-08T10:46:45Z",
          "created_by": "/bin/sh -c #(nop)  CMD [\"/bin/bash\"]",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T22:53:15Z",
          "created_by": "ENV DEBIAN_FRONTEND=noninteractive",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T22:53:15Z",
          "created_by": "ENV TZ=UTC",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T22:53:15Z",
          "created_by": "WORKDIR /app",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T22:57:25Z",
          "created_by": "RUN /bin/sh -c apt-get update \u0026\u0026 apt-get install -y     curl     wget     git     vim     unzip     software-properties-common     apt-transport-https     ca-certificates     gnupg     lsb-release     build-essential     gcc     g++     make     cmake     python2.7     python2.7-dev     python3     python3-dev     python3-pip     python3-venv     r-base     r-base-dev     libssl-dev     libcurl4-openssl-dev     libxml2-dev     libfontconfig1-dev     libharfbuzz-dev     libfribidi-dev     libfreetype6-dev     libpng-dev     libtiff5-dev     libjpeg-dev     \u0026\u0026 rm -rf /var/lib/apt/lists/* # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T22:57:27Z",
          "created_by": "RUN /bin/sh -c curl https://bootstrap.pypa.io/pip/2.7/get-pip.py -o get-pip.py \u0026\u0026     python2.7 get-pip.py \u0026\u0026     rm get-pip.py # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T22:57:27Z",
          "created_by": "RUN /bin/sh -c ln -s /usr/bin/python2.7 /usr/bin/python2 \u0026\u0026     ln -s /usr/bin/python3 /usr/bin/python # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T22:57:27Z",
          "created_by": "COPY requirements-python2.txt requirements-python3.txt requirements-r.txt ./ # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T23:00:37Z",
          "created_by": "RUN /bin/sh -c python2 -m pip install --no-cache-dir -r requirements-python2.txt # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T23:01:56Z",
          "created_by": "RUN /bin/sh -c python3 -m pip install --no-cache-dir -r requirements-python3.txt # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "RUN /bin/sh -c Rscript -e \"install.packages(readLines('requirements-r.txt'), repos='https://cran.rstudio.com/')\" # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "RUN /bin/sh -c useradd -m -s /bin/bash devuser \u0026\u0026     chown -R devuser:devuser /app # buildkit",
          "comment": "buildkit.dockerfile.v0"
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "USER devuser",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "ENV PATH=/home/devuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "ENV PYTHONPATH=/app",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        },
        {
          "created": "2025-09-20T23:10:44Z",
          "created_by": "HEALTHCHECK \u0026{[\"CMD-SHELL\" \"python3 -c \\\"import sys; print('Python 3:', sys.version)\\\" \u0026\u0026         python2 -c \\\"import sys; print('Python 2:', sys.version)\\\" \u0026\u0026         R --version\"] \"30s\" \"10s\" \"5s\" \"0s\" '\\x03'}",
          "comment": "buildkit.dockerfile.v0",
          "empty_layer": true
        }
      ],
      "os": "linux",
      "rootfs": {
        "type": "layers",
        "diff_ids": [
          "sha256:37250a17e932419f4b54e624c819baf38c0025e7f9c4ba0e15af15f14a3d74c3",
          "sha256:f285a80895c537447a3af1aeb534e77e7074cfc0fc63ad3b8d4ac9539ec90eae",
          "sha256:19d688abc07463fa0a04b64bde341879eda4dfd6d02476ba8a3dc2061acde116",
          "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e",
          "sha256:c863fef0e8f8649e5598387fb11477e70e1242d34418782c9a51af388c6051f1",
          "sha256:4162fdb4031ba1de37011c5a9d6aff2f1c70103e3b5663b394b469581405e656",
          "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0",
          "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b",
          "sha256:18d41a068f1d775a1ded11049b2553072ee671ddbcf5905bbbbeac50044f3513",
          "sha256:fc8eff637fb0b182b66636c55c1041a52bb9f067170944ec1c36e99c0528574c"
        ]
      },
      "config": {
        "Cmd": [
          "/bin/bash"
        ],
        "Healthcheck": {
          "Test": [
            "CMD-SHELL",
            "python3 -c \"import sys; print('Python 3:', sys.version)\" \u0026\u0026         python2 -c \"import sys; print('Python 2:', sys.version)\" \u0026\u0026         R --version"
          ],
          "Interval": 30000000000,
          "Timeout": 10000000000,
          "StartPeriod": 5000000000,
          "Retries": 3
        },
        "Env": [
          "PATH=/home/devuser/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
          "DEBIAN_FRONTEND=noninteractive",
          "TZ=UTC",
          "PYTHONPATH=/app"
        ],
        "Labels": {
          "org.opencontainers.image.ref.name": "ubuntu",
          "org.opencontainers.image.version": "20.04"
        },
        "User": "devuser",
        "WorkingDir": "/app"
      }
    },
    "Layers": [
      {
        "Size": 68133376,
        "DiffID": "sha256:37250a17e932419f4b54e624c819baf38c0025e7f9c4ba0e15af15f14a3d74c3"
      },
      {
        "Size": 1536,
        "DiffID": "sha256:f285a80895c537447a3af1aeb534e77e7074cfc0fc63ad3b8d4ac9539ec90eae"
      },
      {
        "Size": 923283968,
        "DiffID": "sha256:19d688abc07463fa0a04b64bde341879eda4dfd6d02476ba8a3dc2061acde116"
      },
      {
        "Size": 15545856,
        "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
      },
      {
        "Size": 3072,
        "DiffID": "sha256:c863fef0e8f8649e5598387fb11477e70e1242d34418782c9a51af388c6051f1"
      },
      {
        "Size": 5120,
        "DiffID": "sha256:4162fdb4031ba1de37011c5a9d6aff2f1c70103e3b5663b394b469581405e656"
      },
      {
        "Size": 277613056,
        "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
      },
      {
        "Size": 814596096,
        "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
      },
      {
        "Size": 281280512,
        "DiffID": "sha256:18d41a068f1d775a1ded11049b2553072ee671ddbcf5905bbbbeac50044f3513"
      },
      {
        "Size": 360448,
        "DiffID": "sha256:fc8eff637fb0b182b66636c55c1041a52bb9f067170944ec1c36e99c0528574c"
      }
    ]
  },
  "Results": [
    {
      "Target": "glinsky/devsecops-multilang:v1.2.0 (ubuntu 20.04)",
      "Class": "os-pkgs",
      "Type": "ubuntu",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2025-4802",
          "PkgID": "libc-bin@2.31-0ubuntu9.17",
          "PkgName": "libc-bin",
          "PkgIdentifier": {
            "PURL": "pkg:deb/ubuntu/libc-bin@2.31-0ubuntu9.17?arch=arm64\u0026distro=ubuntu-20.04",
            "UID": "2f7bc6f96901024"
          },
          "InstalledVersion": "2.31-0ubuntu9.17",
          "FixedVersion": "2.31-0ubuntu9.18",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:37250a17e932419f4b54e624c819baf38c0025e7f9c4ba0e15af15f14a3d74c3"
          },
          "SeveritySource": "ubuntu",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-4802",
          "DataSource": {
            "ID": "ubuntu",
            "Name": "Ubuntu CVE Tracker",
            "URL": "https://git.launchpad.net/ubuntu-cve-tracker"
          },
          "Title": "glibc: static setuid binary dlopen may incorrectly search LD_LIBRARY_PATH",
          "Description": "Untrusted LD_LIBRARY_PATH environment variable vulnerability in the GNU C Library version 2.27 to 2.38 allows attacker controlled loading of dynamically shared library in statically compiled setuid binaries that call dlopen (including internal dlopen calls after setlocale or calls to NSS functions such as getaddrinfo).",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-426"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 7
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2025/05/16/7",
            "http://www.openwall.com/lists/oss-security/2025/05/17/2",
            "https://access.redhat.com/errata/RHSA-2025:8655",
            "https://access.redhat.com/security/cve/CVE-2025-4802",
            "https://bugzilla.redhat.com/2367468",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2367468",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-4802",
            "https://errata.almalinux.org/9/ALSA-2025-8655.html",
            "https://errata.rockylinux.org/RLSA-2025:8686",
            "https://linux.oracle.com/cve/CVE-2025-4802.html",
            "https://linux.oracle.com/errata/ELSA-2025-8686.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-4802",
            "https://sourceware.org/bugzilla/show_bug.cgi?id=32976",
            "https://sourceware.org/cgit/glibc/commit/?id=1e18586c5820e329f741d5c710275e165581380e",
            "https://sourceware.org/cgit/glibc/commit/?id=5451fa962cd0a90a0e2ec1d8910a559ace02bba0",
            "https://ubuntu.com/security/notices/USN-7541-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-4802",
            "https://www.openwall.com/lists/oss-security/2025/05/16/7",
            "https://www.openwall.com/lists/oss-security/2025/05/17/2"
          ],
          "PublishedDate": "2025-05-16T20:15:22.28Z",
          "LastModifiedDate": "2025-06-17T14:09:23.137Z"
        }
      ]
    },
    {
      "Target": "Node.js",
      "Class": "lang-pkgs",
      "Type": "node-pkg",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2021-41182",
          "PkgID": "jquery-ui@1.12.1",
          "PkgName": "jquery-ui",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/matplotlib/backends/web_backend/jquery-ui-1.12.1/package.json",
          "PkgIdentifier": {
            "PURL": "pkg:npm/jquery-ui@1.12.1",
            "UID": "ae7966bef94fdb13"
          },
          "InstalledVersion": "1.12.1",
          "FixedVersion": "1.13.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41182",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "jquery-ui: XSS in the altField option of the datepicker widget",
          "Description": "jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of the `altField` option of the Datepicker widget from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. Any string value passed to the `altField` option is now treated as a CSS selector. A workaround is to not accept the value of the `altField` option from untrusted sources.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ruby-advisory-db": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-41182",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/",
            "https://github.com/advisories/GHSA-9gj3-hwp5-pmwc",
            "https://github.com/jquery-ui-rails/jquery-ui-rails/commit/413265e81f790f795239e07e7e25e01429b2f18d",
            "https://github.com/jquery/jquery-ui",
            "https://github.com/jquery/jquery-ui/commit/32850869d308d5e7c9bf3e3b4d483ea886d373ce",
            "https://github.com/jquery/jquery-ui/pull/1954/commits/6809ce843e5ac4128108ea4c15cbc100653c2b63",
            "https://github.com/jquery/jquery-ui/security/advisories/GHSA-9gj3-hwp5-pmwc",
            "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/jquery-ui-rails/CVE-2021-41182.yml",
            "https://lists.debian.org/debian-lts-announce/2022/01/msg00014.html",
            "https://lists.debian.org/debian-lts-announce/2023/08/msg00040.html",
            "https://lists.fedoraproject.org/archives/list/package-announce",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-41182",
            "https://security.netapp.com/advisory/ntap-20211118-0004",
            "https://security.netapp.com/advisory/ntap-20211118-0004/",
            "https://ubuntu.com/security/notices/USN-6419-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-41182",
            "https://www.drupal.org/sa-contrib-2022-004",
            "https://www.drupal.org/sa-core-2022-002",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html",
            "https://www.tenable.com/security/tns-2022-09"
          ],
          "PublishedDate": "2021-10-26T15:15:10.313Z",
          "LastModifiedDate": "2024-11-21T06:25:41.707Z"
        },
        {
          "VulnerabilityID": "CVE-2021-41183",
          "PkgID": "jquery-ui@1.12.1",
          "PkgName": "jquery-ui",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/matplotlib/backends/web_backend/jquery-ui-1.12.1/package.json",
          "PkgIdentifier": {
            "PURL": "pkg:npm/jquery-ui@1.12.1",
            "UID": "ae7966bef94fdb13"
          },
          "InstalledVersion": "1.12.1",
          "FixedVersion": "1.13.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41183",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "jquery-ui: XSS in *Text options of the datepicker widget",
          "Description": "jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of various `*Text` options of the Datepicker widget from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. The values passed to various `*Text` options are now always treated as pure text, not HTML. A workaround is to not accept the value of the `*Text` options from untrusted sources.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ruby-advisory-db": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-41183",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/",
            "https://bugs.jqueryui.com/ticket/15284",
            "https://github.com/advisories/GHSA-j7qv-pgf6-hvh4",
            "https://github.com/jquery-ui-rails/jquery-ui-rails/commit/413265e81f790f795239e07e7e25e01429b2f18d",
            "https://github.com/jquery/jquery-ui",
            "https://github.com/jquery/jquery-ui/pull/1953",
            "https://github.com/jquery/jquery-ui/security/advisories/GHSA-j7qv-pgf6-hvh4",
            "https://lists.debian.org/debian-lts-announce/2022/01/msg00014.html",
            "https://lists.debian.org/debian-lts-announce/2023/08/msg00040.html",
            "https://lists.fedoraproject.org/archives/list/package-announce",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-41183",
            "https://security.netapp.com/advisory/ntap-20211118-0004",
            "https://security.netapp.com/advisory/ntap-20211118-0004/",
            "https://ubuntu.com/security/notices/USN-6419-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-41183",
            "https://www.drupal.org/sa-contrib-2022-004",
            "https://www.drupal.org/sa-core-2022-001",
            "https://www.drupal.org/sa-core-2022-002",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html",
            "https://www.tenable.com/security/tns-2022-09"
          ],
          "PublishedDate": "2021-10-26T15:15:10.387Z",
          "LastModifiedDate": "2024-11-21T06:25:42.137Z"
        },
        {
          "VulnerabilityID": "CVE-2021-41184",
          "PkgID": "jquery-ui@1.12.1",
          "PkgName": "jquery-ui",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/matplotlib/backends/web_backend/jquery-ui-1.12.1/package.json",
          "PkgIdentifier": {
            "PURL": "pkg:npm/jquery-ui@1.12.1",
            "UID": "ae7966bef94fdb13"
          },
          "InstalledVersion": "1.12.1",
          "FixedVersion": "1.13.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41184",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "jquery-ui: XSS in the 'of' option of the .position() util",
          "Description": "jQuery-UI is the official jQuery user interface library. Prior to version 1.13.0, accepting the value of the `of` option of the `.position()` util from untrusted sources may execute untrusted code. The issue is fixed in jQuery UI 1.13.0. Any string value passed to the `of` option is now treated as a CSS selector. A workaround is to not accept the value of the `of` option from untrusted sources.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ruby-advisory-db": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V2Score": 4.3,
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-41184",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released",
            "https://blog.jqueryui.com/2021/10/jquery-ui-1-13-0-released/",
            "https://github.com/advisories/GHSA-gpqq-952q-5327",
            "https://github.com/jquery-ui-rails/jquery-ui-rails/commit/413265e81f790f795239e07e7e25e01429b2f18d",
            "https://github.com/jquery/jquery-ui",
            "https://github.com/jquery/jquery-ui/commit/effa323f1505f2ce7a324e4f429fa9032c72f280",
            "https://github.com/jquery/jquery-ui/security/advisories/GHSA-gpqq-952q-5327",
            "https://lists.debian.org/debian-lts-announce/2023/08/msg00040.html",
            "https://lists.fedoraproject.org/archives/list/package-announce",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/HVKIOWSXL2RF2ULNAP7PHESYCFSZIJE3/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NXIUUBRVLA4E7G7MMIKCEN75YN7UFERW/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/O74SXYY7RGXREQDQUDQD4BPJ4QQTD2XQ/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SGSY236PYSFYIEBRGDERLA7OSY6D7XL4/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SNXA7XRKGINWSUIPIZ6ZBCTV6N3KSHES/",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-41184",
            "https://security.netapp.com/advisory/ntap-20211118-0004",
            "https://security.netapp.com/advisory/ntap-20211118-0004/",
            "https://ubuntu.com/security/notices/USN-5181-1",
            "https://ubuntu.com/security/notices/USN-6419-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-41184",
            "https://www.drupal.org/sa-core-2022-001",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html",
            "https://www.tenable.com/security/tns-2022-09"
          ],
          "PublishedDate": "2021-10-26T15:15:10.46Z",
          "LastModifiedDate": "2024-11-21T06:25:42.43Z"
        },
        {
          "VulnerabilityID": "CVE-2022-31160",
          "PkgID": "jquery-ui@1.12.1",
          "PkgName": "jquery-ui",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/matplotlib/backends/web_backend/jquery-ui-1.12.1/package.json",
          "PkgIdentifier": {
            "PURL": "pkg:npm/jquery-ui@1.12.1",
            "UID": "ae7966bef94fdb13"
          },
          "InstalledVersion": "1.12.1",
          "FixedVersion": "1.13.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-31160",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory npm",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Anpm"
          },
          "Title": "jqueryui: XSS when refreshing a checkboxradio with an HTML-like initial text label",
          "Description": "jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of jQuery. Versions prior to 1.13.2 are potentially vulnerable to cross-site scripting. Initializing a checkboxradio widget on an input enclosed within a label makes that parent label contents considered as the input label. Calling `.checkboxradio( \"refresh\" )` on such a widget and the initial HTML contained encoded HTML entities will make them erroneously get decoded. This can lead to potentially executing JavaScript code. The bug has been patched in jQuery UI 1.13.2. To remediate the issue, someone who can change the initial HTML can wrap all the non-input contents of the `label` in a `span`.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 3,
            "ruby-advisory-db": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-31160",
            "https://blog.jqueryui.com/2022/07/jquery-ui-1-13-2-released",
            "https://blog.jqueryui.com/2022/07/jquery-ui-1-13-2-released/",
            "https://github.com/advisories/GHSA-h6gj-6jjq-h8g9#:~:text=https%3A//nvd.nist,12/msg00015.html",
            "https://github.com/jquery-ui-rails/jquery-ui-rails/blob/master/VERSIONS.md",
            "https://github.com/jquery-ui-rails/jquery-ui-rails/releases/tag/v8.0.0-release",
            "https://github.com/jquery/jquery-ui",
            "https://github.com/jquery/jquery-ui/commit/8cc5bae1caa1fcf96bf5862c5646c787020ba3f9",
            "https://github.com/jquery/jquery-ui/security/advisories/GHSA-h6gj-6jjq-h8g9",
            "https://github.com/rubysec/ruby-advisory-db/blob/master/gems/jquery-ui-rails/CVE-2022-31160.yml",
            "https://lists.debian.org/debian-lts-announce/2022/12/msg00015.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6XBR3G3JR5ZIOJDO4224M3INXDS2VFDD/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/J5LGNTICB5BRFAG3DHVVELS6H3CZSQMO/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/QB2FJQXCNHO32VGVOC6DY6IPGVE4VDU6/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6XBR3G3JR5ZIOJDO4224M3INXDS2VFDD",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6XBR3G3JR5ZIOJDO4224M3INXDS2VFDD/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/J5LGNTICB5BRFAG3DHVVELS6H3CZSQMO",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/J5LGNTICB5BRFAG3DHVVELS6H3CZSQMO/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QB2FJQXCNHO32VGVOC6DY6IPGVE4VDU6",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QB2FJQXCNHO32VGVOC6DY6IPGVE4VDU6/",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-31160",
            "https://security.netapp.com/advisory/ntap-20220909-0007",
            "https://security.netapp.com/advisory/ntap-20220909-0007/",
            "https://ubuntu.com/security/notices/USN-5181-1",
            "https://ubuntu.com/security/notices/USN-6419-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-31160",
            "https://www.drupal.org/sa-contrib-2022-052"
          ],
          "PublishedDate": "2022-07-20T20:15:08.053Z",
          "LastModifiedDate": "2024-11-21T07:04:01.617Z"
        }
      ]
    },
    {
      "Target": "Python",
      "Class": "lang-pkgs",
      "Type": "python-pkg",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2024-23334",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-23334",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: follow_symlinks directory traversal vulnerability",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. When using aiohttp as a web server and configuring static routes, it is necessary to specify the root path for static files. Additionally, the option 'follow_symlinks' can be used to determine whether to follow symbolic links outside the static root directory. When 'follow_symlinks' is set to True, there is no validation to check if reading a file is within the root directory. This can lead to directory traversal vulnerabilities, resulting in unauthorized access to arbitrary files on the system, even when symlinks are not present.  Disabling follow_symlinks and using a reverse proxy are encouraged mitigations.  Version 3.9.2 fixes this issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "ghsa": 3,
            "nvd": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.9
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-23334",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/1c335944d6a8b1298baf179b7c0b3069f10c514b",
            "https://github.com/aio-libs/aiohttp/pull/8079",
            "https://github.com/aio-libs/aiohttp/pull/8079/files",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5h86-8mv2-jq9f",
            "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2024-24.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-23334",
            "https://ubuntu.com/security/notices/USN-6991-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-23334"
          ],
          "PublishedDate": "2024-01-29T23:15:08.563Z",
          "LastModifiedDate": "2024-11-21T08:57:32.007Z"
        },
        {
          "VulnerabilityID": "CVE-2024-30251",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.4",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-30251",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: DoS when trying to parse malformed POST requests",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. In affected versions an attacker can send a specially crafted POST (multipart/form-data) request. When the aiohttp server processes it, the server will enter an infinite loop and be unable to process any further requests. An attacker can stop the application from serving requests after sending a single request. This issue has been addressed in version 3.9.4. Users are advised to upgrade. Users unable to upgrade may manually apply a patch to their systems. Please see the linked GHSA for instructions.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-835"
          ],
          "VendorSeverity": {
            "ghsa": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "http://www.openwall.com/lists/oss-security/2024/05/02/4",
            "https://access.redhat.com/security/cve/CVE-2024-30251",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/7eecdff163ccf029fbb1ddc9de4169d4aaeb6597",
            "https://github.com/aio-libs/aiohttp/commit/cebe526b9c34dc3a3da9140409db63014bc4cf19",
            "https://github.com/aio-libs/aiohttp/commit/f21c6f2ca512a026ce7f0f6c6311f62d6a638866",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-5m98-qgg9-wh84",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-30251",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-30251",
            "https://www.openwall.com/lists/oss-security/2024/05/02/4"
          ],
          "PublishedDate": "2024-05-02T14:15:09.627Z",
          "LastModifiedDate": "2025-08-21T15:23:59.153Z"
        },
        {
          "VulnerabilityID": "CVE-2023-47627",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.8.6",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-47627",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-aiohttp: numerous issues in HTTP parser with header parsing",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. The HTTP parser in AIOHTTP has numerous problems with header parsing, which could lead to request smuggling. This parser is only used when AIOHTTP_NO_EXTENSIONS is enabled (or not using a prebuilt wheel). These bugs have been addressed in commit `d5c12ba89` which has been included in release version 3.8.6. Users are advised to upgrade. There are no known workarounds for these issues.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-444"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-47627",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/d5c12ba890557a575c313bb3017910d7616fce3d",
            "https://github.com/aio-libs/aiohttp/commit/d5c12ba890557a575c313bb3017910d7616fce3d (v3.8.6)",
            "https://github.com/aio-libs/aiohttp/releases/tag/v3.8.6",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg",
            "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2023-246.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FUSJVQ7OQ55RWL4XAX2F5EZ73N4ZSH6U",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FUSJVQ7OQ55RWL4XAX2F5EZ73N4ZSH6U/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VDKQ6HM3KNDU4OQI476ZWT4O7DMSIT35",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/VDKQ6HM3KNDU4OQI476ZWT4O7DMSIT35/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQYQL6WV535EEKSNH7KRARLLMOW5WXDM",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQYQL6WV535EEKSNH7KRARLLMOW5WXDM/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-47627",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-47627"
          ],
          "PublishedDate": "2023-11-14T21:15:12.82Z",
          "LastModifiedDate": "2024-11-21T08:30:33.583Z"
        },
        {
          "VulnerabilityID": "CVE-2023-49081",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-49081",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: HTTP request modification",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Improper validation made it possible for an attacker to modify the HTTP request (e.g. to insert a new header) or create a new HTTP request if the attacker controls the HTTP version. The vulnerability only occurs if the attacker can control the HTTP version of the request. This issue has been patched in version 3.9.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:N",
              "V3Score": 7.2
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:L/A:N",
              "V3Score": 5.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-49081",
            "https://gist.github.com/jnovikov/184afb593d9c2114d77f508e0ccd508e",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/1e86b777e61cf4eefc7d92fa57fa19dcc676013b",
            "https://github.com/aio-libs/aiohttp/pull/7835",
            "https://github.com/aio-libs/aiohttp/pull/7835/files",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-q3qx-c6g2-7pw2",
            "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2023-250.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TY5SI6NK5243DEEDQUFKQKW5GQNKQUMA",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSYWMP64ZFCTC3VO6RY6EC6VSSMV6I3A",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-49081",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-49081"
          ],
          "PublishedDate": "2023-11-30T07:15:08.723Z",
          "LastModifiedDate": "2024-11-21T08:32:46.897Z"
        },
        {
          "VulnerabilityID": "CVE-2023-49082",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-49082",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: CRLF injection if user controls the HTTP method using aiohttp client",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Improper validation makes it possible for an attacker to modify the HTTP request (e.g. insert a new header) or even create a new HTTP request if the attacker controls the HTTP method. The vulnerability occurs only if the attacker can control the HTTP method (GET, POST etc.) of the request. If the attacker can control the HTTP version of the request it will be able to modify the request (request smuggling). This issue has been patched in version 3.9.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-20",
            "CWE-93"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 1,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-49082",
            "https://gist.github.com/jnovikov/7f411ae9fe6a9a7804cf162a3bdbb44b",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/4075c653fb67a29740bf9ac050bb02d10a57343a (v3.9.0b1)",
            "https://github.com/aio-libs/aiohttp/commit/493f06797654c383242f0e8007f6e06b818a1fbc (master)",
            "https://github.com/aio-libs/aiohttp/commit/e4ae01c2077d2cfa116aa82e4ff6866857f7c466",
            "https://github.com/aio-libs/aiohttp/pull/7806/files",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-qvrw-v9rv-5rjx",
            "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2023-251.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TY5SI6NK5243DEEDQUFKQKW5GQNKQUMA",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WSYWMP64ZFCTC3VO6RY6EC6VSSMV6I3A",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-49082",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-49082"
          ],
          "PublishedDate": "2023-11-29T20:15:08.18Z",
          "LastModifiedDate": "2024-11-21T08:32:47.033Z"
        },
        {
          "VulnerabilityID": "CVE-2024-23829",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-23829",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-aiohttp: http request smuggling",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Security-sensitive parts of the Python HTTP parser retained minor differences in allowable character sets, that must trigger error handling to robustly match frame boundaries of proxies in order to protect against injection of additional requests. Additionally, validation could trigger exceptions that were not handled consistently with processing of other malformed input.  Being more lenient than internet standards require could, depending on deployment environment, assist in request smuggling. The unhandled exception could cause excessive resource consumption on the application server and/or its logging facilities. This vulnerability exists due to an incomplete fix for CVE-2023-47627. Version 3.9.2 fixes this vulnerability.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-444"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:L",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-23829",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/33ccdfb0a12690af5bb49bda2319ec0907fa7827",
            "https://github.com/aio-libs/aiohttp/pull/3235",
            "https://github.com/aio-libs/aiohttp/pull/8074",
            "https://github.com/aio-libs/aiohttp/pull/8074/files",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8qpw-xqxj-h4r2",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-gfw2-4jvh-wgfg",
            "https://github.com/pypa/advisory-database/tree/main/vulns/aiohttp/PYSEC-2024-26.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ICUOCFGTB25WUT336BZ4UNYLSZOUVKBD/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/XXWVZIVAYWEBHNRIILZVB3R3SDQNNAA7/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-23829",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-23829"
          ],
          "PublishedDate": "2024-01-29T23:15:08.767Z",
          "LastModifiedDate": "2024-11-21T08:58:30.683Z"
        },
        {
          "VulnerabilityID": "CVE-2024-27306",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.9.4",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-27306",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: XSS on index pages for static file handling",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. A XSS vulnerability exists on index pages for static file handling. This vulnerability is fixed in 3.9.4. We have always recommended using a reverse proxy server (e.g. nginx) for serving static files. Users following the recommendation are unaffected. Other users can disable `show_index` if unable to upgrade.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79",
            "CWE-80"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-27306",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397",
            "https://github.com/aio-libs/aiohttp/commit/28335525d1eac015a7e7584137678cbb6ff19397 (v3.9.4)",
            "https://github.com/aio-libs/aiohttp/pull/8319",
            "https://github.com/aio-libs/aiohttp/pull/8319/files",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-7gpw-8wmc-pm8g",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/2EXRGTN2WG7VZLUZ7WOXU5GQJKCPPHKP/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/NWEI6NIHZ3G7DURDZVMRK7ZEFC2BTD3U/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZIVBMPEY7WWOFMC3CWXFBRQPFECV4SW3/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-27306",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-27306"
          ],
          "PublishedDate": "2024-04-18T15:15:29.05Z",
          "LastModifiedDate": "2025-08-21T00:45:38.12Z"
        },
        {
          "VulnerabilityID": "CVE-2024-52304",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.10.11",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-52304",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: aiohttp vulnerable to request smuggling due to incorrect parsing of chunk extensions",
          "Description": "aiohttp is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.10.11, the Python parser parses newlines in chunk extensions incorrectly which can lead to request smuggling vulnerabilities under certain conditions. If a pure Python version of aiohttp is installed (i.e. without the usual C extensions) or `AIOHTTP_NO_EXTENSIONS` is enabled, then an attacker may be able to execute a request smuggling attack to bypass certain firewalls or proxy protections. Version 3.10.11 fixes the issue.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-444"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-52304",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/259edc369075de63e6f3a4eaade058c62af0df71",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-8495-4g3g-x7pr",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-52304",
            "https://ubuntu.com/security/notices/USN-7642-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-52304"
          ],
          "PublishedDate": "2024-11-18T21:15:06.5Z",
          "LastModifiedDate": "2025-08-15T17:36:18.507Z"
        },
        {
          "VulnerabilityID": "GHSA-pjjw-qhg8-p2p9",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.8.6",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://github.com/advisories/GHSA-pjjw-qhg8-p2p9",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp has vulnerable dependency that is vulnerable to request smuggling",
          "Description": "### Summary\nllhttp 8.1.1 is vulnerable to two request smuggling vulnerabilities.\nDetails have not been disclosed yet, so refer to llhttp for future information.\nThe issue is resolved by using llhttp 9+ (which is included in aiohttp 3.8.6+).",
          "Severity": "MEDIUM",
          "VendorSeverity": {
            "ghsa": 2
          },
          "References": [
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/996de2629ef6b4c2934a7c04dfd49d0950d4c43b",
            "https://github.com/aio-libs/aiohttp/commit/bcc416e533796d04fb8124ef1e7686b1f338767a",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-pjjw-qhg8-p2p9"
          ],
          "PublishedDate": "2023-11-27T23:15:38Z",
          "LastModifiedDate": "2023-11-27T23:15:38Z"
        },
        {
          "VulnerabilityID": "CVE-2025-53643",
          "PkgName": "aiohttp",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/aiohttp-3.8.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/aiohttp@3.8.5",
            "UID": "5492cf19e66acd61"
          },
          "InstalledVersion": "3.8.5",
          "FixedVersion": "3.12.14",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-53643",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "aiohttp: AIOHTTP HTTP Request/Response Smuggling",
          "Description": "AIOHTTP is an asynchronous HTTP client/server framework for asyncio and Python. Prior to version 3.12.14, the Python parser is vulnerable to a request smuggling vulnerability due to not parsing trailer sections of an HTTP request. If a pure Python version of aiohttp is installed (i.e. without the usual C extensions) or AIOHTTP_NO_EXTENSIONS is enabled, then an attacker may be able to execute a request smuggling attack to bypass certain firewalls or proxy protections. Version 3.12.14 contains a patch for this issue.",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-444"
          ],
          "VendorSeverity": {
            "ghsa": 1,
            "nvd": 3,
            "redhat": 1
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.7
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-53643",
            "https://github.com/aio-libs/aiohttp",
            "https://github.com/aio-libs/aiohttp/commit/e8d774f635dc6d1cd3174d0e38891da5de0e2b6a",
            "https://github.com/aio-libs/aiohttp/security/advisories/GHSA-9548-qrrj-x5pj",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-53643",
            "https://www.cve.org/CVERecord?id=CVE-2025-53643"
          ],
          "PublishedDate": "2025-07-14T21:15:27.827Z",
          "LastModifiedDate": "2025-08-14T20:40:05.493Z"
        },
        {
          "VulnerabilityID": "CVE-2024-21503",
          "PkgName": "black",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/black-23.7.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/black@23.7.0",
            "UID": "e0122eed3dd34e77"
          },
          "InstalledVersion": "23.7.0",
          "FixedVersion": "24.3.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-21503",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "psf/black: ReDoS via the lines_with_leading_tabs_expanded() function in strings.py file",
          "Description": "Versions of the package black before 24.3.0 are vulnerable to Regular Expression Denial of Service (ReDoS) via the lines_with_leading_tabs_expanded function in the strings.py file. An attacker could exploit this vulnerability by crafting a malicious input that causes a denial of service.\r\rExploiting this vulnerability is possible when running Black on untrusted input, or if you habitually put thousands of leading tab characters in your docstrings.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-1333",
            "CWE-75"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "redhat": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-21503",
            "https://github.com/psf/black",
            "https://github.com/psf/black/commit/f00093672628d212b8965a8993cee8bedf5fe9b8",
            "https://github.com/psf/black/releases/tag/24.3.0",
            "https://github.com/pypa/advisory-database/tree/main/vulns/black/PYSEC-2024-48.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-21503",
            "https://security.snyk.io/vuln/SNYK-PYTHON-BLACK-6256273",
            "https://www.cve.org/CVERecord?id=CVE-2024-21503"
          ],
          "PublishedDate": "2024-03-19T05:15:09.447Z",
          "LastModifiedDate": "2024-11-21T08:54:34.26Z"
        },
        {
          "VulnerabilityID": "CVE-2023-37920",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/certifi-2021.10.8.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2021.10.8",
            "UID": "e83503f39ca7b3d6"
          },
          "InstalledVersion": "2021.10.8",
          "FixedVersion": "2023.7.22",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-37920",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Removal of e-Tugra root certificate",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi prior to version 2023.07.22 recognizes \"e-Tugra\" root certificates. e-Tugra's root certificates were subject to an investigation prompted by reporting of security issues in their systems. Certifi 2023.07.22 removes root certificates from \"e-Tugra\" from the root store.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 4,
            "ghsa": 3,
            "nvd": 4,
            "oracle-oval": 2,
            "photon": 4,
            "redhat": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 9.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:7753",
            "https://access.redhat.com/security/cve/CVE-2023-37920",
            "https://bugzilla.redhat.com/2226586",
            "https://bugzilla.redhat.com/2242493",
            "https://errata.almalinux.org/9/ALSA-2023-7753.html",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/8fb96ed81f71e7097ed11bc4d9b19afd7ea5c909",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-xqr8-7jwr-rhp7",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2023-135.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/C-HrP1SEq1A",
            "https://linux.oracle.com/cve/CVE-2023-37920.html",
            "https://linux.oracle.com/errata/ELSA-2024-0133.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5EX6NG7WUFNUKGFHLM35KHHU3GAKXRTG/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-37920",
            "https://security.netapp.com/advisory/ntap-20240912-0002",
            "https://security.netapp.com/advisory/ntap-20240912-0002/",
            "https://www.cve.org/CVERecord?id=CVE-2023-37920"
          ],
          "PublishedDate": "2023-07-25T21:15:10.827Z",
          "LastModifiedDate": "2025-02-13T13:50:15.813Z"
        },
        {
          "VulnerabilityID": "CVE-2022-23491",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/certifi-2021.10.8.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2021.10.8",
            "UID": "e83503f39ca7b3d6"
          },
          "InstalledVersion": "2021.10.8",
          "FixedVersion": "2022.12.07",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-23491",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: untrusted root certificates",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi 2022.12.07 removes root certificates from \"TrustCor\" from the root store. These are in the process of being removed from Mozilla's trust store. TrustCor's root certificates are being removed pursuant to an investigation prompted by media reporting that TrustCor's ownership also operated a business that produced spyware. Conclusions of Mozilla's investigation can be found in the linked google group discussion.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "amazon": 3,
            "ghsa": 2,
            "nvd": 3,
            "photon": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:C/C:N/I:H/A:N",
              "V3Score": 6.8
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-23491",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/9e9e840925d7b8e76c76fdac1fab7e6e88c1c3b8",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-43fp-rhv2-5gv8",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2022-42986.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/oxX69KFvsm4/m/yLohoVqtCgAJ",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-23491",
            "https://security.netapp.com/advisory/ntap-20230223-0010",
            "https://security.netapp.com/advisory/ntap-20230223-0010/",
            "https://ubuntu.com/security/notices/USN-5761-1",
            "https://ubuntu.com/security/notices/USN-5761-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-23491"
          ],
          "PublishedDate": "2022-12-07T22:15:09.87Z",
          "LastModifiedDate": "2025-02-12T17:36:19.373Z"
        },
        {
          "VulnerabilityID": "CVE-2024-39689",
          "PkgName": "certifi",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/certifi-2021.10.8.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/certifi@2021.10.8",
            "UID": "e83503f39ca7b3d6"
          },
          "InstalledVersion": "2021.10.8",
          "FixedVersion": "2024.7.4",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-39689",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-certifi: Remove root certificates from `GLOBALTRUST` from the root store",
          "Description": "Certifi is a curated collection of Root Certificates for validating the trustworthiness of SSL certificates while verifying the identity of TLS hosts. Certifi starting in 2021.5.30 and prior to 2024.7.4 recognized root certificates from `GLOBALTRUST`. Certifi 2024.7.04 removes root certificates from `GLOBALTRUST` from the root store. These are in the process of being removed from Mozilla's trust store. `GLOBALTRUST`'s root certificates are being removed pursuant to an investigation which identified \"long-running and unresolved compliance issues.\"",
          "Severity": "LOW",
          "CweIDs": [
            "CWE-345"
          ],
          "VendorSeverity": {
            "amazon": 1,
            "ghsa": 1,
            "nvd": 3,
            "photon": 3,
            "redhat": 1
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:L/I:N/A:N",
              "V3Score": 3.7
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-39689",
            "https://github.com/certifi/python-certifi",
            "https://github.com/certifi/python-certifi/commit/bd8153872e9c6fc98f4023df9c2deaffea2fa463",
            "https://github.com/certifi/python-certifi/security/advisories/GHSA-248v-346w-9cwc",
            "https://github.com/pypa/advisory-database/tree/main/vulns/certifi/PYSEC-2024-230.yaml",
            "https://groups.google.com/a/mozilla.org/g/dev-security-policy/c/XpknYMPO8dI",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-39689",
            "https://security.netapp.com/advisory/ntap-20241206-0001",
            "https://security.netapp.com/advisory/ntap-20241206-0001/",
            "https://www.cve.org/CVERecord?id=CVE-2024-39689"
          ],
          "PublishedDate": "2024-07-05T19:15:10.247Z",
          "LastModifiedDate": "2025-02-15T00:15:13.183Z"
        },
        {
          "VulnerabilityID": "CVE-2024-3651",
          "PkgName": "idna",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/idna-2.10.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/idna@2.10",
            "UID": "dbbd6c97e86d65b4"
          },
          "InstalledVersion": "2.10",
          "FixedVersion": "3.7",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-3651",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-idna: potential DoS via resource consumption via specially crafted inputs to idna.encode()",
          "Description": "A vulnerability was identified in the kjd/idna library, specifically within the `idna.encode()` function, affecting version 3.6. The issue arises from the function's handling of crafted input strings, which can lead to quadratic complexity and consequently, a denial of service condition. This vulnerability is triggered by a crafted input that causes the `idna.encode()` function to process the input with considerable computational load, significantly increasing the processing time in a quadratic manner relative to the input size.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-400"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "ghsa": 2,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.2
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:3846",
            "https://access.redhat.com/security/cve/CVE-2024-3651",
            "https://bugzilla.redhat.com/2274779",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2274779",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-3651",
            "https://errata.almalinux.org/9/ALSA-2024-3846.html",
            "https://errata.rockylinux.org/RLSA-2024:3846",
            "https://github.com/kjd/idna",
            "https://github.com/kjd/idna/commit/1d365e17e10d72d0b7876316fc7b9ca0eebdd38d",
            "https://github.com/kjd/idna/security/advisories/GHSA-jjg7-2v4v-x38h",
            "https://github.com/pypa/advisory-database/tree/main/vulns/idna/PYSEC-2024-60.yaml",
            "https://huntr.com/bounties/93d78d07-d791-4b39-a845-cbfabc44aadb",
            "https://linux.oracle.com/cve/CVE-2024-3651.html",
            "https://linux.oracle.com/errata/ELSA-2024-8365.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-3651",
            "https://ubuntu.com/security/notices/USN-6780-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-3651"
          ],
          "PublishedDate": "2024-07-07T18:15:09.827Z",
          "LastModifiedDate": "2025-08-19T19:48:28.797Z"
        },
        {
          "VulnerabilityID": "CVE-2024-22421",
          "PkgName": "jupyterlab",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/jupyterlab-4.0.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/jupyterlab@4.0.5",
            "UID": "1075b19ee7284b7d"
          },
          "InstalledVersion": "4.0.5",
          "FixedVersion": "4.0.11, 3.6.7",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-22421",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "JupyterLab is an extensible environment for interactive and reproducib ...",
          "Description": "JupyterLab is an extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture. Users of JupyterLab who click on a malicious link may get their `Authorization` and `XSRFToken` tokens exposed to a third party when running an older `jupyter-server` version. JupyterLab versions 4.1.0b2, 4.0.11, and 3.6.7 are patched. No workaround has been identified, however users should ensure to upgrade `jupyter-server` to version 2.7.2 or newer which includes a redirect vulnerability fix.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-23",
            "CWE-200"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 3,
            "nvd": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 6.5
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:L",
              "V3Score": 7.6
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 6.5
            }
          },
          "References": [
            "https://github.com/jupyterlab/jupyterlab",
            "https://github.com/jupyterlab/jupyterlab/commit/19bd9b96cb2e77170a67e43121637d0b5619e8c6",
            "https://github.com/jupyterlab/jupyterlab/commit/1ef7a4fa0202ebdf663e1cc0b45c8813a34a0b96",
            "https://github.com/jupyterlab/jupyterlab/commit/fccd83dc4441da0384ee3fd1322c3b2d9ad4caaa",
            "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-44cc-43rp-5947",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UQJKNRDRFMKGVRIYNNN6CKMNJDNYWO2H",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UQJKNRDRFMKGVRIYNNN6CKMNJDNYWO2H/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-22421"
          ],
          "PublishedDate": "2024-01-19T21:15:09.87Z",
          "LastModifiedDate": "2024-11-21T08:56:15.343Z"
        },
        {
          "VulnerabilityID": "CVE-2024-43805",
          "PkgName": "jupyterlab",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/jupyterlab-4.0.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/jupyterlab@4.0.5",
            "UID": "1075b19ee7284b7d"
          },
          "InstalledVersion": "4.0.5",
          "FixedVersion": "3.6.8, 4.2.5",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-43805",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "jupyterlab is an extensible environment for interactive and reproducib ...",
          "Description": "jupyterlab is an extensible environment for interactive and reproducible computing, based on the Jupyter Notebook Architecture. This vulnerability depends on user interaction by opening a malicious notebook with Markdown cells, or Markdown file using JupyterLab preview feature. A malicious user can access any data that the attacked user has access to as well as perform arbitrary requests acting as the attacked user. JupyterLab v3.6.8, v4.2.5 and Jupyter Notebook v7.2.2 have been patched to resolve this issue. Users are advised to upgrade. There is no workaround for the underlying DOM Clobbering susceptibility. However, select plugins can be disabled on deployments which cannot update in a timely fashion to minimise the risk. These are: 1. `@jupyterlab/mathjax-extension:plugin` - users will loose ability to preview mathematical equations. 2. `@jupyterlab/markdownviewer-extension:plugin` - users will loose ability to open Markdown previews. 3. `@jupyterlab/mathjax2-extension:plugin` (if installed with optional `jupyterlab-mathjax2` package) - an older version of the mathjax plugin for JupyterLab 4.x. To disable these extensions run: ```jupyter labextension disable @jupyterlab/markdownviewer-extension:plugin \u0026\u0026 jupyter labextension disable @jupyterlab/mathjax-extension:plugin \u0026\u0026 jupyter labextension disable @jupyterlab/mathjax2-extension:plugin ``` in bash.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 3,
            "nvd": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:L/A:L",
              "V3Score": 7.6
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://github.com/jupyterlab/jupyterlab",
            "https://github.com/jupyterlab/jupyterlab/commit/06ad9de836f155add7d3d651ef936cc4c5ea8093",
            "https://github.com/jupyterlab/jupyterlab/commit/88e24baac551196f9cb3de16bd060a7ab1597674",
            "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-9q39-rmj3-p4r2",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-43805"
          ],
          "PublishedDate": "2024-08-28T20:15:07.963Z",
          "LastModifiedDate": "2024-08-30T15:56:16.477Z"
        },
        {
          "VulnerabilityID": "CVE-2024-22420",
          "PkgName": "jupyterlab",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/jupyterlab-4.0.5.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/jupyterlab@4.0.5",
            "UID": "1075b19ee7284b7d"
          },
          "InstalledVersion": "4.0.5",
          "FixedVersion": "4.0.11",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-22420",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "JupyterLab is an extensible environment for interactive and reproducib ...",
          "Description": "JupyterLab is an extensible environment for interactive and reproducible computing, based on the Jupyter Notebook and Architecture. This vulnerability depends on user interaction by opening a malicious Markdown file using JupyterLab preview feature. A malicious user can access any data that the attacked user has access to as well as perform arbitrary requests acting as the attacked user. JupyterLab version 4.0.11 has been patched. Users are advised to upgrade. Users unable to upgrade should disable the table of contents extension.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-79"
          ],
          "VendorSeverity": {
            "bitnami": 2,
            "ghsa": 2,
            "nvd": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 6.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://github.com/jupyterlab/jupyterlab",
            "https://github.com/jupyterlab/jupyterlab/commit/dda0033cd49449572d077bbecd33b18d8d05f48a",
            "https://github.com/jupyterlab/jupyterlab/commit/e1b3aabab603878e46add445a3114e838411d2df",
            "https://github.com/jupyterlab/jupyterlab/security/advisories/GHSA-4m77-cmpx-vjc4",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UQJKNRDRFMKGVRIYNNN6CKMNJDNYWO2H",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UQJKNRDRFMKGVRIYNNN6CKMNJDNYWO2H/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-22420"
          ],
          "PublishedDate": "2024-01-19T21:15:09.667Z",
          "LastModifiedDate": "2024-11-21T08:56:15.203Z"
        },
        {
          "VulnerabilityID": "CVE-2021-41495",
          "PkgName": "numpy",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/numpy-1.16.6.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/numpy@1.16.6",
            "UID": "1c67618a079e3643"
          },
          "InstalledVersion": "1.16.6",
          "FixedVersion": "1.19",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41495",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "numpy: NULL pointer dereference in numpy.sort in in the PyArray_DescrNew() due to missing return-value validation",
          "Description": "Null Pointer Dereference vulnerability exists in numpy.sort in NumPy \u0026lt and 1.19 in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-476"
          ],
          "VendorSeverity": {
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 3.5,
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-41495",
            "https://github.com/advisories/GHSA-5545-2q6w-2gh6",
            "https://github.com/numpy/numpy",
            "https://github.com/numpy/numpy/issues/19038",
            "https://github.com/numpy/numpy/pull/20960",
            "https://github.com/numpy/numpy/pull/20984 (backport)",
            "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-856.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-41495",
            "https://ubuntu.com/security/notices/USN-5763-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-41495",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-12-17T20:15:08.477Z",
          "LastModifiedDate": "2024-11-21T06:26:18.94Z"
        },
        {
          "VulnerabilityID": "CVE-2021-33430",
          "PkgName": "numpy",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/numpy-1.16.6.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/numpy@1.16.6",
            "UID": "1c67618a079e3643"
          },
          "InstalledVersion": "1.16.6",
          "FixedVersion": "1.21",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33430",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "numpy: buffer overflow in the PyArray_NewFromDescr_int() in ctors.c",
          "Description": "A Buffer Overflow vulnerability exists in NumPy 1.9.x in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. NOTE: The vendor does not agree this is a vulneraility; In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-120"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.3
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 3.5,
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-33430",
            "https://github.com/numpy/numpy",
            "https://github.com/numpy/numpy/commit/16f7824b4d935b6aee98298ca4123d57174a6f2e (v1.22.0.dev0)",
            "https://github.com/numpy/numpy/commit/ae317fd9ff3e79c0eac357d723bfc29cbd625f2e",
            "https://github.com/numpy/numpy/issues/18939",
            "https://github.com/numpy/numpy/pull/18989",
            "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-854.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-33430",
            "https://ubuntu.com/security/notices/USN-5763-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-33430"
          ],
          "PublishedDate": "2021-12-17T19:15:07.5Z",
          "LastModifiedDate": "2024-11-21T06:08:48.743Z"
        },
        {
          "VulnerabilityID": "CVE-2021-34141",
          "PkgName": "numpy",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/numpy-1.16.6.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/numpy@1.16.6",
            "UID": "1c67618a079e3643"
          },
          "InstalledVersion": "1.16.6",
          "FixedVersion": "1.22",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-34141",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "numpy: incomplete string comparison in the numpy.core component",
          "Description": "An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. NOTE: the vendor states that this reported code behavior is \"completely harmless.\"",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-697"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 1,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V2Score": 5,
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 2.2
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-34141",
            "https://github.com/advisories/GHSA-fpfv-jqm9-f5jm",
            "https://github.com/numpy/numpy",
            "https://github.com/numpy/numpy/commit/eeef9d4646103c3b1afd3085f1393f2b3f9575b2 (v1.23.0.dev0)",
            "https://github.com/numpy/numpy/issues/18993",
            "https://github.com/numpy/numpy/issues/18993#issuecomment-1010735102",
            "https://github.com/pypa/advisory-database/tree/main/vulns/numpy/PYSEC-2021-855.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-34141",
            "https://ubuntu.com/security/notices/USN-5763-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-34141",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-12-17T19:15:07.543Z",
          "LastModifiedDate": "2024-11-21T06:09:56.397Z"
        },
        {
          "VulnerabilityID": "CVE-2021-41496",
          "PkgName": "numpy",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/numpy-1.16.6.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/numpy@1.16.6",
            "UID": "1c67618a079e3643"
          },
          "InstalledVersion": "1.16.6",
          "FixedVersion": "1.19",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-41496",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "numpy: buffer overflow in the array_from_pyobj() in fortranobject.c",
          "Description": "Buffer overflow in the array_from_pyobj function of fortranobject.c in NumPy \u003c 1.19, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally)",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-120"
          ],
          "VendorSeverity": {
            "cbl-mariner": 2,
            "ghsa": 2,
            "nvd": 2,
            "photon": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            },
            "nvd": {
              "V2Vector": "AV:L/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 2.1,
              "V3Score": 5.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2021-41496",
            "https://github.com/numpy/numpy",
            "https://github.com/numpy/numpy/commit/271010f1037150e95017f803f4214b8861e528f2",
            "https://github.com/numpy/numpy/issues/19000",
            "https://github.com/numpy/numpy/pull/20630",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-41496",
            "https://ubuntu.com/security/notices/USN-5763-1",
            "https://www.cve.org/CVERecord?id=CVE-2021-41496",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-12-17T20:15:08.517Z",
          "LastModifiedDate": "2024-11-21T06:26:19.13Z"
        },
        {
          "VulnerabilityID": "CVE-2021-3572",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/pip-20.3.4.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@20.3.4",
            "UID": "5d6fd9d2bbfeaa67"
          },
          "InstalledVersion": "20.3.4",
          "FixedVersion": "21.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-3572",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pip: Incorrect handling of unicode separators in git references",
          "Description": "A flaw was found in python-pip in the way it handled Unicode separators in git references. A remote attacker could possibly use this issue to install a different revision on a repository. The highest threat from this vulnerability is to data integrity. This is fixed in python-pip version 21.1.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 1,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 3,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 5.7
            },
            "nvd": {
              "V2Vector": "AV:N/AC:M/Au:S/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:R/S:U/C:N/I:H/A:N",
              "V2Score": 3.5,
              "V3Score": 5.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:H/UI:R/S:U/C:N/I:H/A:N",
              "V3Score": 4.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2021:3254",
            "https://access.redhat.com/security/cve/CVE-2021-3572",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1962856",
            "https://github.com/advisories/GHSA-5xp3-jfq3-5q8x",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2021-437.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/e46bdda9711392fec0c45c1175bae6db847cb30b",
            "https://github.com/pypa/pip/issues/10042",
            "https://github.com/pypa/pip/issues/10042#issuecomment-857452480",
            "https://github.com/pypa/pip/pull/9827",
            "https://github.com/skazi0/CVE-2021-3572/blob/master/CVE-2021-3572-v9.0.1.patch",
            "https://linux.oracle.com/cve/CVE-2021-3572.html",
            "https://linux.oracle.com/errata/ELSA-2023-12349.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2021-3572",
            "https://packetstormsecurity.com/files/162712/USN-4961-1.txt",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://ubuntu.com/security/notices/USN-4961-2",
            "https://www.cve.org/CVERecord?id=CVE-2021-3572",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-11-10T18:15:09.51Z",
          "LastModifiedDate": "2024-11-21T06:21:52.473Z"
        },
        {
          "VulnerabilityID": "CVE-2023-5752",
          "PkgName": "pip",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/pip-20.3.4.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pip@20.3.4",
            "UID": "5d6fd9d2bbfeaa67"
          },
          "InstalledVersion": "20.3.4",
          "FixedVersion": "23.3",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-5752",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pip: Mercurial configuration injectable in repo revision when installing via pip",
          "Description": "When installing a package from a Mercurial VCS URL  (ie \"pip install \nhg+...\") with pip prior to v23.3, the specified Mercurial revision could\n be used to inject arbitrary configuration options to the \"hg clone\" \ncall (ie \"--config\"). Controlling the Mercurial configuration can modify\n how and which repository is installed. This vulnerability does not \naffect users who aren't installing from Mercurial.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-77"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 1,
            "bitnami": 1,
            "cbl-mariner": 2,
            "ghsa": 2,
            "nvd": 1,
            "redhat": 1
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 5.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:N/I:L/A:N",
              "V3Score": 3.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-5752",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pip/PYSEC-2023-228.yaml",
            "https://github.com/pypa/pip",
            "https://github.com/pypa/pip/commit/389cb799d0da9a840749fcd14878928467ed49b4",
            "https://github.com/pypa/pip/pull/12306",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/622OZXWG72ISQPLM5Y57YCVIMWHD4C3U/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/65UKKF5LBHEFDCUSPBHUN4IHYX7SRMHH/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/FXUVMJM25PUAZRQZBF54OFVKTY3MINPW/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KFC2SPFG5FLCZBYY2K3T5MFW2D22NG6E/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YBSB3SUPQ3VIFYUMHPO3MEQI4BJAXKCZ/",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL",
            "https://mail.python.org/archives/list/security-announce@python.org/thread/F4PL35U6X4VVHZ5ILJU3PWUWN7H7LZXL/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-5752",
            "https://www.cve.org/CVERecord?id=CVE-2023-5752"
          ],
          "PublishedDate": "2023-10-25T18:17:44.867Z",
          "LastModifiedDate": "2025-02-13T18:16:01.057Z"
        },
        {
          "VulnerabilityID": "CVE-2024-3772",
          "PkgName": "pydantic",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/pydantic-2.1.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pydantic@2.1.1",
            "UID": "8313bc8895685c1a"
          },
          "InstalledVersion": "2.1.1",
          "FixedVersion": "2.4.0, 1.10.13",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-3772",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-pydantic: regular expression denial of service via crafted email string",
          "Description": "Regular expression denial of service in Pydanic \u003c 2.4.0, \u003c 1.10.13 allows remote attackers to cause denial of service via a crafted email string.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-1333"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "photon": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-3772",
            "https://github.com/pydantic/pydantic",
            "https://github.com/pydantic/pydantic/commit/59d8f38fd6220e3917c53785dbc70317d6f8e631",
            "https://github.com/pydantic/pydantic/commit/59d8f38fd6220e3917c53785dbc70317d6f8e631 (v1.0.13)",
            "https://github.com/pydantic/pydantic/commit/e4393ae6145c4dadff739990bb0116c6dec3441b",
            "https://github.com/pydantic/pydantic/commit/e4393ae6145c4dadff739990bb0116c6dec3441b (v2.4.0)",
            "https://github.com/pydantic/pydantic/pull/7360",
            "https://github.com/pydantic/pydantic/pull/7673",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6JBZLMSH4GAZOVBMT2JUO2LXHY7M2ALI",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6JBZLMSH4GAZOVBMT2JUO2LXHY7M2ALI/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-3772",
            "https://ubuntu.com/security/notices/USN-7101-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-3772"
          ],
          "PublishedDate": "2024-04-15T03:16:07.987Z",
          "LastModifiedDate": "2025-02-13T18:18:10.987Z"
        },
        {
          "VulnerabilityID": "CVE-2023-32681",
          "PkgName": "requests",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/requests-2.27.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.27.1",
            "UID": "6e9b3295fceb944b"
          },
          "InstalledVersion": "2.27.1",
          "FixedVersion": "2.31.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-32681",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-requests: Unintended leak of Proxy-Authorization header",
          "Description": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-200"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "nvd": 2,
            "oracle-oval": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:4350",
            "https://access.redhat.com/security/cve/CVE-2023-32681",
            "https://bugzilla.redhat.com/2209469",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2209469",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32681",
            "https://errata.almalinux.org/9/ALSA-2023-4350.html",
            "https://errata.rockylinux.org/RLSA-2023:4520",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5",
            "https://github.com/psf/requests/releases/tag/v2.31.0",
            "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q",
            "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml",
            "https://linux.oracle.com/cve/CVE-2023-32681.html",
            "https://linux.oracle.com/errata/ELSA-2023-7050.html",
            "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-32681",
            "https://security.gentoo.org/glsa/202309-08",
            "https://ubuntu.com/security/notices/USN-6155-1",
            "https://ubuntu.com/security/notices/USN-6155-2",
            "https://ubuntu.com/security/notices/USN-7568-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-32681"
          ],
          "PublishedDate": "2023-05-26T18:15:14.147Z",
          "LastModifiedDate": "2025-02-13T17:16:32.583Z"
        },
        {
          "VulnerabilityID": "CVE-2024-35195",
          "PkgName": "requests",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/requests-2.27.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.27.1",
            "UID": "6e9b3295fceb944b"
          },
          "InstalledVersion": "2.27.1",
          "FixedVersion": "2.32.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-35195",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "requests: subsequent requests to the same host ignore cert verification",
          "Description": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-670"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:7049",
            "https://access.redhat.com/security/cve/CVE-2024-35195",
            "https://bugzilla.redhat.com/2282114",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2282114",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-35195",
            "https://errata.almalinux.org/9/ALSA-2025-7049.html",
            "https://errata.rockylinux.org/RLSA-2025:0012",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
            "https://github.com/psf/requests/pull/6655",
            "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56",
            "https://linux.oracle.com/cve/CVE-2024-35195.html",
            "https://linux.oracle.com/errata/ELSA-2025-7049.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-35195",
            "https://www.cve.org/CVERecord?id=CVE-2024-35195"
          ],
          "PublishedDate": "2024-05-20T21:15:09.99Z",
          "LastModifiedDate": "2024-11-21T09:19:54.51Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47081",
          "PkgName": "requests",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/requests-2.27.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.27.1",
            "UID": "6e9b3295fceb944b"
          },
          "InstalledVersion": "2.27.1",
          "FixedVersion": "2.32.4",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47081",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "requests: Requests vulnerable to .netrc credentials leak via malicious URLs",
          "Description": "Requests is a HTTP library. Due to a URL parsing issue, Requests releases prior to 2.32.4 may leak .netrc credentials to third parties for specific maliciously-crafted URLs. Users should upgrade to version 2.32.4 to receive a fix. For older versions of Requests, use of the .netrc file can be disabled with `trust_env=False` on one's Requests Session.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-522"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "http://seclists.org/fulldisclosure/2025/Jun/2",
            "http://www.openwall.com/lists/oss-security/2025/06/03/11",
            "http://www.openwall.com/lists/oss-security/2025/06/03/9",
            "http://www.openwall.com/lists/oss-security/2025/06/04/1",
            "http://www.openwall.com/lists/oss-security/2025/06/04/6",
            "https://access.redhat.com/errata/RHSA-2025:12519",
            "https://access.redhat.com/security/cve/CVE-2024-47081",
            "https://bugzilla.redhat.com/2371272",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2371272",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-47081",
            "https://errata.almalinux.org/9/ALSA-2025-12519.html",
            "https://errata.rockylinux.org/RLSA-2025:13234",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef",
            "https://github.com/psf/requests/pull/6965",
            "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7",
            "https://linux.oracle.com/cve/CVE-2024-47081.html",
            "https://linux.oracle.com/errata/ELSA-2025-14999.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47081",
            "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env",
            "https://seclists.org/fulldisclosure/2025/Jun/2",
            "https://ubuntu.com/security/notices/USN-7568-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47081",
            "https://www.openwall.com/lists/oss-security/2025/06/03/9"
          ],
          "PublishedDate": "2025-06-09T18:15:24.983Z",
          "LastModifiedDate": "2025-06-12T16:06:47.857Z"
        },
        {
          "VulnerabilityID": "CVE-2024-35195",
          "PkgName": "requests",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/requests-2.31.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.31.0",
            "UID": "35a99506d84a4e98"
          },
          "InstalledVersion": "2.31.0",
          "FixedVersion": "2.32.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-35195",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "requests: subsequent requests to the same host ignore cert verification",
          "Description": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-670"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:7049",
            "https://access.redhat.com/security/cve/CVE-2024-35195",
            "https://bugzilla.redhat.com/2282114",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2282114",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-35195",
            "https://errata.almalinux.org/9/ALSA-2025-7049.html",
            "https://errata.rockylinux.org/RLSA-2025:0012",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
            "https://github.com/psf/requests/pull/6655",
            "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56",
            "https://linux.oracle.com/cve/CVE-2024-35195.html",
            "https://linux.oracle.com/errata/ELSA-2025-7049.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-35195",
            "https://www.cve.org/CVERecord?id=CVE-2024-35195"
          ],
          "PublishedDate": "2024-05-20T21:15:09.99Z",
          "LastModifiedDate": "2024-11-21T09:19:54.51Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47081",
          "PkgName": "requests",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/requests-2.31.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.31.0",
            "UID": "35a99506d84a4e98"
          },
          "InstalledVersion": "2.31.0",
          "FixedVersion": "2.32.4",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47081",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "requests: Requests vulnerable to .netrc credentials leak via malicious URLs",
          "Description": "Requests is a HTTP library. Due to a URL parsing issue, Requests releases prior to 2.32.4 may leak .netrc credentials to third parties for specific maliciously-crafted URLs. Users should upgrade to version 2.32.4 to receive a fix. For older versions of Requests, use of the .netrc file can be disabled with `trust_env=False` on one's Requests Session.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-522"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "http://seclists.org/fulldisclosure/2025/Jun/2",
            "http://www.openwall.com/lists/oss-security/2025/06/03/11",
            "http://www.openwall.com/lists/oss-security/2025/06/03/9",
            "http://www.openwall.com/lists/oss-security/2025/06/04/1",
            "http://www.openwall.com/lists/oss-security/2025/06/04/6",
            "https://access.redhat.com/errata/RHSA-2025:12519",
            "https://access.redhat.com/security/cve/CVE-2024-47081",
            "https://bugzilla.redhat.com/2371272",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2371272",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-47081",
            "https://errata.almalinux.org/9/ALSA-2025-12519.html",
            "https://errata.rockylinux.org/RLSA-2025:13234",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/96ba401c1296ab1dda74a2365ef36d88f7d144ef",
            "https://github.com/psf/requests/pull/6965",
            "https://github.com/psf/requests/security/advisories/GHSA-9hjg-9r4m-mvj7",
            "https://linux.oracle.com/cve/CVE-2024-47081.html",
            "https://linux.oracle.com/errata/ELSA-2025-14999.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47081",
            "https://requests.readthedocs.io/en/latest/api/#requests.Session.trust_env",
            "https://seclists.org/fulldisclosure/2025/Jun/2",
            "https://ubuntu.com/security/notices/USN-7568-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-47081",
            "https://www.openwall.com/lists/oss-security/2025/06/03/9"
          ],
          "PublishedDate": "2025-06-09T18:15:24.983Z",
          "LastModifiedDate": "2025-06-12T16:06:47.857Z"
        },
        {
          "VulnerabilityID": "CVE-2020-13092",
          "PkgName": "scikit-learn",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/scikit_learn-0.20.4-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/scikit-learn@0.20.4",
            "UID": "f0b5cf383a536e68"
          },
          "InstalledVersion": "0.20.4",
          "Status": "affected",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-13092",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute  ...",
          "Description": "scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-502"
          ],
          "VendorSeverity": {
            "ghsa": 4,
            "nvd": 4
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 7.5,
              "V3Score": 9.8
            }
          },
          "References": [
            "https://github.com/0FuzzingQ/vuln/blob/master/sklearn%20unserialize.md",
            "https://github.com/pypa/advisory-database/tree/main/vulns/scikit-learn/PYSEC-2020-107.yaml",
            "https://github.com/scikit-learn/scikit-learn",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-13092",
            "https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations"
          ],
          "PublishedDate": "2020-05-15T19:15:12.277Z",
          "LastModifiedDate": "2024-11-21T05:00:39.113Z"
        },
        {
          "VulnerabilityID": "CVE-2024-5206",
          "PkgName": "scikit-learn",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/scikit_learn-0.20.4-py2.7.egg-info/PKG-INFO",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/scikit-learn@0.20.4",
            "UID": "f0b5cf383a536e68"
          },
          "InstalledVersion": "0.20.4",
          "FixedVersion": "1.5.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-5206",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "scikit-learn: Possible sensitive data leak",
          "Description": "A sensitive data leakage vulnerability was identified in scikit-learn's TfidfVectorizer, specifically in versions up to and including 1.4.1.post1, which was fixed in version 1.5.0. The vulnerability arises from the unexpected storage of all tokens present in the training data within the `stop_words_` attribute, rather than only storing the subset of tokens required for the TF-IDF technique to function. This behavior leads to the potential leakage of sensitive information, as the `stop_words_` attribute could contain tokens that were meant to be discarded and not stored, such as passwords or keys. The impact of this vulnerability varies based on the nature of the data being processed by the vectorizer.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-921",
            "CWE-922"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-5206",
            "https://github.com/pypa/advisory-database/tree/main/vulns/scikit-learn/PYSEC-2024-110.yaml",
            "https://github.com/scikit-learn/scikit-learn",
            "https://github.com/scikit-learn/scikit-learn/commit/70ca21f106b603b611da73012c9ade7cd8e438b8",
            "https://huntr.com/bounties/14bc0917-a85b-4106-a170-d09d5191517c",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-5206",
            "https://www.cve.org/CVERecord?id=CVE-2024-5206"
          ],
          "PublishedDate": "2024-06-06T19:16:06.363Z",
          "LastModifiedDate": "2024-11-21T09:47:11.143Z"
        },
        {
          "VulnerabilityID": "CVE-2024-5206",
          "PkgName": "scikit-learn",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/scikit_learn-1.3.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/scikit-learn@1.3.0",
            "UID": "e765e8a679439af0"
          },
          "InstalledVersion": "1.3.0",
          "FixedVersion": "1.5.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-5206",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "scikit-learn: Possible sensitive data leak",
          "Description": "A sensitive data leakage vulnerability was identified in scikit-learn's TfidfVectorizer, specifically in versions up to and including 1.4.1.post1, which was fixed in version 1.5.0. The vulnerability arises from the unexpected storage of all tokens present in the training data within the `stop_words_` attribute, rather than only storing the subset of tokens required for the TF-IDF technique to function. This behavior leads to the potential leakage of sensitive information, as the `stop_words_` attribute could contain tokens that were meant to be discarded and not stored, such as passwords or keys. The impact of this vulnerability varies based on the nature of the data being processed by the vectorizer.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-921",
            "CWE-922"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.7
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-5206",
            "https://github.com/pypa/advisory-database/tree/main/vulns/scikit-learn/PYSEC-2024-110.yaml",
            "https://github.com/scikit-learn/scikit-learn",
            "https://github.com/scikit-learn/scikit-learn/commit/70ca21f106b603b611da73012c9ade7cd8e438b8",
            "https://huntr.com/bounties/14bc0917-a85b-4106-a170-d09d5191517c",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-5206",
            "https://www.cve.org/CVERecord?id=CVE-2024-5206"
          ],
          "PublishedDate": "2024-06-06T19:16:06.363Z",
          "LastModifiedDate": "2024-11-21T09:47:11.143Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40897",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/setuptools-44.1.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.1.1",
            "UID": "f357e3a6fdcd53c0"
          },
          "InstalledVersion": "44.1.1",
          "FixedVersion": "65.5.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40897",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa-setuptools: Regular Expression Denial of Service (ReDoS) in package_index.py",
          "Description": "Python Packaging Authority (PyPA) setuptools before 65.5.1 allows remote attackers to cause a denial of service via HTML in a crafted package or custom PackageIndex page. There is a Regular Expression Denial of Service (ReDoS) in package_index.py.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-1333"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "bitnami": 2,
            "cbl-mariner": 2,
            "ghsa": 3,
            "nvd": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 5.9
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:0952",
            "https://access.redhat.com/security/cve/CVE-2022-40897",
            "https://bugzilla.redhat.com/2158559",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2158559",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40897",
            "https://errata.almalinux.org/9/ALSA-2023-0952.html",
            "https://errata.rockylinux.org/RLSA-2023:0952",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2022-43012.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/fe8a98e696241487ba6ac9f91faa38ade939ec5d/setuptools/package_index.py#L200",
            "https://github.com/pypa/setuptools/commit/43a9c9bfa6aa626ec2a22540bea28d2ca77964be",
            "https://github.com/pypa/setuptools/compare/v65.5.0...v65.5.1",
            "https://github.com/pypa/setuptools/issues/3659",
            "https://linux.oracle.com/cve/CVE-2022-40897.html",
            "https://linux.oracle.com/errata/ELSA-2024-2987.html",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ADES3NLOE5QJKBLGNZNI2RGVOSQXA37R",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/YNA2BAH2ACBZ4TVJZKFLCR7L23BG5C3H",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40897",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495",
            "https://pyup.io/vulnerabilities/CVE-2022-40897/52495/",
            "https://security.netapp.com/advisory/ntap-20230214-0001",
            "https://security.netapp.com/advisory/ntap-20230214-0001/",
            "https://security.netapp.com/advisory/ntap-20240621-0006",
            "https://security.netapp.com/advisory/ntap-20240621-0006/",
            "https://setuptools.pypa.io/en/latest",
            "https://ubuntu.com/security/notices/USN-5817-1",
            "https://www.cve.org/CVERecord?id=CVE-2022-40897"
          ],
          "PublishedDate": "2022-12-23T00:15:13.987Z",
          "LastModifiedDate": "2024-11-21T07:22:13.787Z"
        },
        {
          "VulnerabilityID": "CVE-2024-6345",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/setuptools-44.1.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.1.1",
            "UID": "f357e3a6fdcd53c0"
          },
          "InstalledVersion": "44.1.1",
          "FixedVersion": "70.0.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-6345",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "pypa/setuptools: Remote code execution via download functions in the package_index module in pypa/setuptools",
          "Description": "A vulnerability in the package_index module of pypa/setuptools versions up to 69.1.1 allows for remote code execution via its download functions. These functions, which are used to download packages from URLs provided by users or retrieved from package index servers, are susceptible to code injection. If these functions are exposed to user-controlled inputs, such as package URLs, they can execute arbitrary commands on the system. The issue is fixed in version 70.0.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-94"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "rocky": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "bitnami": {
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:6726",
            "https://access.redhat.com/security/cve/CVE-2024-6345",
            "https://bugzilla.redhat.com/2297771",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2297771",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-6345",
            "https://errata.almalinux.org/9/ALSA-2024-6726.html",
            "https://errata.rockylinux.org/RLSA-2024:6726",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0",
            "https://github.com/pypa/setuptools/pull/4332",
            "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5",
            "https://linux.oracle.com/cve/CVE-2024-6345.html",
            "https://linux.oracle.com/errata/ELSA-2024-6726.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-6345",
            "https://ubuntu.com/security/notices/USN-7002-1",
            "https://www.cve.org/CVERecord?id=CVE-2024-6345"
          ],
          "PublishedDate": "2024-07-15T01:15:01.73Z",
          "LastModifiedDate": "2024-11-21T09:49:28.17Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47273",
          "PkgName": "setuptools",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/setuptools-44.1.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/setuptools@44.1.1",
            "UID": "f357e3a6fdcd53c0"
          },
          "InstalledVersion": "44.1.1",
          "FixedVersion": "78.1.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47273",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "setuptools: Path Traversal Vulnerability in setuptools PackageIndex",
          "Description": "setuptools is a package that allows users to download, build, install, upgrade, and uninstall Python packages. A path traversal vulnerability in `PackageIndex` is present in setuptools prior to version 78.1.1. An attacker would be allowed to write files to arbitrary locations on the filesystem with the permissions of the process running the Python code, which could escalate to remote code execution depending on the context. Version 78.1.1 fixes the issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-22"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 3,
            "azure": 3,
            "bitnami": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 8.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:H/A:L",
              "V3Score": 7.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:13578",
            "https://access.redhat.com/security/cve/CVE-2025-47273",
            "https://bugzilla.redhat.com/2366982",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2366982",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-47273",
            "https://errata.almalinux.org/9/ALSA-2025-13578.html",
            "https://errata.rockylinux.org/RLSA-2025:11036",
            "https://github.com/pypa/advisory-database/tree/main/vulns/setuptools/PYSEC-2025-49.yaml",
            "https://github.com/pypa/setuptools",
            "https://github.com/pypa/setuptools/blob/6ead555c5fb29bc57fe6105b1bffc163f56fd558/setuptools/package_index.py#L810C1-L825C88",
            "https://github.com/pypa/setuptools/commit/250a6d17978f9f6ac3ac887091f2d32886fbbb0b",
            "https://github.com/pypa/setuptools/issues/4946",
            "https://github.com/pypa/setuptools/security/advisories/GHSA-5rjg-fvgr-3xxf",
            "https://linux.oracle.com/cve/CVE-2025-47273.html",
            "https://linux.oracle.com/errata/ELSA-2025-9940.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00035.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47273",
            "https://ubuntu.com/security/notices/USN-7544-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47273"
          ],
          "PublishedDate": "2025-05-17T16:15:19.11Z",
          "LastModifiedDate": "2025-06-12T16:29:01.66Z"
        },
        {
          "VulnerabilityID": "CVE-2024-47874",
          "PkgName": "starlette",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/starlette-0.27.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/starlette@0.27.0",
            "UID": "755a59d2d18348fb"
          },
          "InstalledVersion": "0.27.0",
          "FixedVersion": "0.40.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-47874",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "starlette: Starlette Denial of service (DoS) via multipart/form-data",
          "Description": "Starlette is an Asynchronous Server Gateway Interface (ASGI) framework/toolkit. Prior to version 0.40.0, Starlette treats `multipart/form-data` parts without a `filename` as text form fields and buffers those in byte strings with no size limit. This allows an attacker to upload arbitrary large form fields and cause Starlette to both slow down significantly due to excessive memory allocations and copy operations, and also consume more and more memory until the server starts swapping and grinds to a halt, or the OS terminates the server process with an OOM error. Uploading multiple such requests in parallel may be enough to render a service practically unusable, even if reasonable request size limits are enforced by a reverse proxy in front of Starlette. This Denial of service (DoS) vulnerability affects all applications built with Starlette (or FastAPI) accepting form requests. Verison 0.40.0 fixes this issue.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "VendorSeverity": {
            "ghsa": 3,
            "redhat": 3
          },
          "CVSS": {
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2024-47874",
            "https://github.com/encode/starlette",
            "https://github.com/encode/starlette/commit/fd038f3070c302bff17ef7d173dbb0b007617733",
            "https://github.com/encode/starlette/security/advisories/GHSA-f96h-pmfr-66vw",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-47874",
            "https://www.cve.org/CVERecord?id=CVE-2024-47874"
          ],
          "PublishedDate": "2024-10-15T16:15:05.26Z",
          "LastModifiedDate": "2024-11-21T17:15:17.99Z"
        },
        {
          "VulnerabilityID": "CVE-2025-54121",
          "PkgName": "starlette",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/starlette-0.27.0.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/starlette@0.27.0",
            "UID": "755a59d2d18348fb"
          },
          "InstalledVersion": "0.27.0",
          "FixedVersion": "0.47.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-54121",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "starlette: Starlette denial-of-service",
          "Description": "Starlette is a lightweight ASGI (Asynchronous Server Gateway Interface) framework/toolkit, designed for building async web services in Python. In versions 0.47.1 and below, when parsing a multi-part form with large files (greater than the default max spool size) starlette will block the main thread to roll the file over to disk. This blocks the event thread which means the application can't accept new connections. The UploadFile code has a minor bug where instead of just checking for self._in_memory, the logic should also check if the additional bytes will cause a rollover. The vulnerability is fixed in version 0.47.2.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-770"
          ],
          "VendorSeverity": {
            "ghsa": 2,
            "redhat": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-54121",
            "https://github.com/encode/starlette",
            "https://github.com/encode/starlette/blob/fa5355442753f794965ae1af0f87f9fec1b9a3de/starlette/datastructures.py#L436C5-L447C14",
            "https://github.com/encode/starlette/commit/9f7ec2eb512fcc3fe90b43cb9dd9e1d08696bec1",
            "https://github.com/encode/starlette/discussions/2927#discussioncomment-13721403",
            "https://github.com/encode/starlette/security/advisories/GHSA-2c2j-9gv5-cj73",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-54121",
            "https://www.cve.org/CVERecord?id=CVE-2025-54121"
          ],
          "PublishedDate": "2025-07-21T20:15:41.827Z",
          "LastModifiedDate": "2025-07-22T13:05:40.573Z"
        },
        {
          "VulnerabilityID": "CVE-2025-47287",
          "PkgName": "tornado",
          "PkgPath": "usr/local/lib/python3.8/dist-packages/tornado-6.4.2.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/tornado@6.4.2",
            "UID": "453a9c46c652abf3"
          },
          "InstalledVersion": "6.4.2",
          "FixedVersion": "6.5",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:651f5dd3f5ed68facf8b58bcdc3ea21123260b90f7bf3dd30f128440e1fe747b"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-47287",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "tornado: Tornado Multipart Form-Data Denial of Service",
          "Description": "Tornado is a Python web framework and asynchronous networking library. When Tornado's ``multipart/form-data`` parser encounters certain errors, it logs a warning but continues trying to parse the remainder of the data. This allows remote attackers to generate an extremely high volume of logs, constituting a DoS attack. This DoS is compounded by the fact that the logging subsystem is synchronous. All versions of Tornado prior to 6.5.0 are affected. The vulnerable parser is enabled by default. Upgrade to Tornado version 6.50 to receive a patch. As a workaround, risk can be mitigated by blocking `Content-Type: multipart/form-data` in a proxy.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-770"
          ],
          "VendorSeverity": {
            "alma": 3,
            "amazon": 2,
            "ghsa": 3,
            "oracle-oval": 3,
            "photon": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:8136",
            "https://access.redhat.com/security/cve/CVE-2025-47287",
            "https://bugzilla.redhat.com/2366703",
            "https://errata.almalinux.org/9/ALSA-2025-8136.html",
            "https://github.com/tornadoweb/tornado",
            "https://github.com/tornadoweb/tornado/commit/b39b892bf78fe8fea01dd45199aa88307e7162f3",
            "https://github.com/tornadoweb/tornado/security/advisories/GHSA-7cx3-6m66-7c5m",
            "https://linux.oracle.com/cve/CVE-2025-47287.html",
            "https://linux.oracle.com/errata/ELSA-2025-8664.html",
            "https://lists.debian.org/debian-lts-announce/2025/05/msg00038.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-47287",
            "https://ubuntu.com/security/notices/USN-7547-1",
            "https://www.cve.org/CVERecord?id=CVE-2025-47287"
          ],
          "PublishedDate": "2025-05-15T22:15:18.827Z",
          "LastModifiedDate": "2025-05-29T06:15:23.09Z"
        },
        {
          "VulnerabilityID": "CVE-2024-37891",
          "PkgName": "urllib3",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/urllib3-1.26.18.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/urllib3@1.26.18",
            "UID": "98d3552266870153"
          },
          "InstalledVersion": "1.26.18",
          "FixedVersion": "1.26.19, 2.2.2",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-37891",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "urllib3: proxy-authorization request header is not stripped during cross-origin redirects",
          "Description": " urllib3 is a user-friendly HTTP client library for Python. When using urllib3's proxy support with `ProxyManager`, the `Proxy-Authorization` header is only sent to the configured proxy, as expected. However, when sending HTTP requests *without* using urllib3's proxy support, it's possible to accidentally configure the `Proxy-Authorization` header even though it won't have any effect as the request is not using a forwarding proxy or a tunneling proxy. In those cases, urllib3 doesn't treat the `Proxy-Authorization` HTTP header as one carrying authentication material and thus doesn't strip the header on cross-origin redirects. Because this is a highly unlikely scenario, we believe the severity of this vulnerability is low for almost all users. Out of an abundance of caution urllib3 will automatically strip the `Proxy-Authorization` header during cross-origin redirects to avoid the small chance that users are doing this on accident. Users should use urllib3's proxy support or disable automatic redirects to achieve safe processing of the `Proxy-Authorization` header, but we still decided to strip the header by default in order to further protect users who aren't using the correct approach. We believe the number of usages affected by this advisory is low. It requires all of the following to be true to be exploited: 1. Setting the `Proxy-Authorization` header without using urllib3's built-in proxy support. 2. Not disabling HTTP redirects. 3. Either not using an HTTPS origin server or for the proxy or target origin to redirect to a malicious origin. Users are advised to update to either version 1.26.19 or version 2.2.2. Users unable to upgrade may use the `Proxy-Authorization` header with urllib3's `ProxyManager`, disable HTTP redirects using `redirects=False` when sending requests, or not user the `Proxy-Authorization` header as mitigations.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-669"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.4
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 4.4
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2024:9458",
            "https://access.redhat.com/security/cve/CVE-2024-37891",
            "https://bugzilla.redhat.com/2292788",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2292788",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-37891",
            "https://errata.almalinux.org/9/ALSA-2024-9458.html",
            "https://errata.rockylinux.org/RLSA-2024:5309",
            "https://github.com/urllib3/urllib3",
            "https://github.com/urllib3/urllib3/commit/40b6d1605814dd1db0a46e202d6e56f2e4c9a468",
            "https://github.com/urllib3/urllib3/commit/accff72ecc2f6cf5a76d9570198a93ac7c90270e",
            "https://github.com/urllib3/urllib3/security/advisories/GHSA-34jh-p97f-mpxf",
            "https://linux.oracle.com/cve/CVE-2024-37891.html",
            "https://linux.oracle.com/errata/ELSA-2024-9458.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-37891",
            "https://security.netapp.com/advisory/ntap-20240822-0003/",
            "https://ubuntu.com/security/notices/USN-7084-1",
            "https://ubuntu.com/security/notices/USN-7084-2",
            "https://www.cve.org/CVERecord?id=CVE-2024-37891",
            "https://www.vicarius.io/vsociety/posts/proxy-authorization-header-handling-vulnerability-in-urllib3-cve-2024-37891"
          ],
          "PublishedDate": "2024-06-17T20:15:13.45Z",
          "LastModifiedDate": "2024-11-21T09:24:28.953Z"
        },
        {
          "VulnerabilityID": "CVE-2025-50181",
          "PkgName": "urllib3",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/urllib3-1.26.18.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/urllib3@1.26.18",
            "UID": "98d3552266870153"
          },
          "InstalledVersion": "1.26.18",
          "FixedVersion": "2.5.0",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:3e5eb2b53d1dfcf9635f78c917d79335dc319c13ec524b424c488de1f08e79f0"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2025-50181",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "urllib3: urllib3 redirects are not disabled when retries are disabled on PoolManager instantiation",
          "Description": "urllib3 is a user-friendly HTTP client library for Python. Prior to 2.5.0, it is possible to disable redirects for all requests by instantiating a PoolManager and specifying retries in a way that disable redirects. By default, requests and botocore users are not affected. An application attempting to mitigate SSRF or open redirect vulnerabilities by disabling redirects at the PoolManager level will remain vulnerable. This issue has been patched in version 2.5.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-601"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "azure": 2,
            "ghsa": 2,
            "nvd": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 5.3
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2025-50181",
            "https://github.com/urllib3/urllib3",
            "https://github.com/urllib3/urllib3/commit/f05b1329126d5be6de501f9d1e3e36738bc08857",
            "https://github.com/urllib3/urllib3/security/advisories/GHSA-pq67-6m6q-mj2v",
            "https://nvd.nist.gov/vuln/detail/CVE-2025-50181",
            "https://ubuntu.com/security/notices/USN-7599-1",
            "https://ubuntu.com/security/notices/USN-7599-2",
            "https://www.cve.org/CVERecord?id=CVE-2025-50181"
          ],
          "PublishedDate": "2025-06-19T01:15:24.453Z",
          "LastModifiedDate": "2025-09-18T13:51:10.24Z"
        },
        {
          "VulnerabilityID": "CVE-2022-40898",
          "PkgName": "wheel",
          "PkgPath": "usr/local/lib/python2.7/dist-packages/wheel-0.37.1.dist-info/METADATA",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/wheel@0.37.1",
            "UID": "e41e08b3baea6005"
          },
          "InstalledVersion": "0.37.1",
          "FixedVersion": "0.38.1",
          "Status": "fixed",
          "Layer": {
            "DiffID": "sha256:489d48e1df748df3fb52a077b753c26144293e50ba43bbe9d33b6fa448b4245e"
          },
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-40898",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-wheel: remote attackers can cause denial of service via attacker controlled input to wheel cli",
          "Description": "An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 3,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:6712",
            "https://access.redhat.com/security/cve/CVE-2022-40898",
            "https://bugzilla.redhat.com/2165864",
            "https://errata.almalinux.org/9/ALSA-2023-6712.html",
            "https://github.com/advisories/GHSA-qwmp-2cf2-g9g6",
            "https://github.com/pypa/advisory-database/tree/main/vulns/wheel/PYSEC-2022-43017.yaml",
            "https://github.com/pypa/wheel",
            "https://github.com/pypa/wheel/blob/main/src/wheel/wheelfile.py#L18",
            "https://github.com/pypa/wheel/commit/88f02bc335d5404991e532e7f3b0fc80437bf4e0",
            "https://linux.oracle.com/cve/CVE-2022-40898.html",
            "https://linux.oracle.com/errata/ELSA-2023-6712.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-40898",
            "https://pypi.org/project/wheel",
            "https://pypi.org/project/wheel/",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages",
            "https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages/",
            "https://pyup.io/vulnerabilities/CVE-2022-40898/51499",
            "https://ubuntu.com/security/notices/USN-5821-1",
            "https://ubuntu.com/security/notices/USN-5821-2",
            "https://ubuntu.com/security/notices/USN-5821-3",
            "https://www.cve.org/CVERecord?id=CVE-2022-40898"
          ],
          "PublishedDate": "2022-12-23T00:15:14.043Z",
          "LastModifiedDate": "2025-04-15T16:15:19.237Z"
        }
      ]
    },
    {
      "Target": "/usr/local/lib/R/site-library/openssl/doc/keys.html",
      "Class": "secret",
      "Secrets": [
        {
          "RuleID": "private-key",
          "Category": "AsymmetricPrivateKey",
          "Severity": "HIGH",
          "Title": "Asymmetric Private Key",
          "StartLine": 422,
          "EndLine": 424,
          "Code": {
            "Lines": [
              {
                "Number": 420,
                "Content": "\u003cpre class=\"r\"\u003e\u003ccode\u003ecat(write_pem(key, password = NULL))\u003c/code\u003e\u003c/pre\u003e",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "\u003cpre class=\"r\"\u003e\u003ccode\u003ecat(write_pem(key, password = NULL))\u003c/code\u003e\u003c/pre\u003e",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 421,
                "Content": "\u003cpre\u003e\u003ccode\u003e-----BEGIN PRIVATE KEY-----",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "\u003cpre\u003e\u003ccode\u003e-----BEGIN PRIVATE KEY-----",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 422,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": true,
                "LastCause": false
              },
              {
                "Number": 423,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 424,
                "Content": "********************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "********************************************************",
                "FirstCause": false,
                "LastCause": true
              },
              {
                "Number": 425,
                "Content": "-----END PRIVATE KEY-----\u003c/code\u003e\u003c/pre\u003e",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "-----END PRIVATE KEY-----\u003c/code\u003e\u003c/pre\u003e",
                "FirstCause": false,
                "LastCause": false
              }
            ]
          },
          "Match": "****************************************************************",
          "Layer": {
            "DiffID": "sha256:18d41a068f1d775a1ded11049b2553072ee671ddbcf5905bbbbeac50044f3513",
            "CreatedBy": "RUN /bin/sh -c Rscript -e \"install.packages(readLines('requirements-r.txt'), repos='https://cran.rstudio.com/')\" # buildkit"
          },
          "Offset": 625727
        },
        {
          "RuleID": "private-key",
          "Category": "AsymmetricPrivateKey",
          "Severity": "HIGH",
          "Title": "Asymmetric Private Key",
          "StartLine": 430,
          "EndLine": 434,
          "Code": {
            "Lines": [
              {
                "Number": 428,
                "Content": "\u003cpre class=\"r\"\u003e\u003ccode\u003ecat(write_pem(key, password = \u0026quot;supersecret\u0026quot;))\u003c/code\u003e\u003c/pre\u003e",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "\u003cpre class=\"r\"\u003e\u003ccode\u003ecat(write_pem(key, password = \u0026quot;supersecret\u0026quot;))\u003c/code\u003e\u003c/pre\u003e",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 429,
                "Content": "\u003cpre\u003e\u003ccode\u003e-----BEGIN ENCRYPTED PRIVATE KEY-----",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "\u003cpre\u003e\u003ccode\u003e-----BEGIN ENCRYPTED PRIVATE KEY-----",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 430,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": true,
                "LastCause": false
              },
              {
                "Number": 431,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 432,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 433,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": false,
                "LastCause": false
              },
              {
                "Number": 434,
                "Content": "****************************************************************",
                "IsCause": true,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "****************************************************************",
                "FirstCause": false,
                "LastCause": true
              },
              {
                "Number": 435,
                "Content": "-----END ENCRYPTED PRIVATE KEY-----\u003c/code\u003e\u003c/pre\u003e",
                "IsCause": false,
                "Annotation": "",
                "Truncated": false,
                "Highlighted": "-----END ENCRYPTED PRIVATE KEY-----\u003c/code\u003e\u003c/pre\u003e",
                "FirstCause": false,
                "LastCause": false
              }
            ]
          },
          "Match": "****************************************************************",
          "Layer": {
            "DiffID": "sha256:18d41a068f1d775a1ded11049b2553072ee671ddbcf5905bbbbeac50044f3513",
            "CreatedBy": "RUN /bin/sh -c Rscript -e \"install.packages(readLines('requirements-r.txt'), repos='https://cran.rstudio.com/')\" # buildkit"
          },
          "Offset": 626236
        }
      ]
    }
  ]
}
